#!/usr/bin/env node
// Generates pkg/dist/chem-wasm-lens.esm.js — a self-contained CDN bundle.
// Run after: wasm-pack build --target web
//
// Usage:
//   node scripts/build_cdn.mjs
//
// Output:
//   pkg/dist/chem-wasm-lens.esm.js  (~615 KB uncompressed, ~200 KB gzip)
//   Wasm binary (~411 KB) is inlined as base64 — no external fetch required.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dir = dirname(fileURLToPath(import.meta.url));
const root  = join(__dir, '..');
const pkg   = join(root, 'pkg');

const wasmBytes  = readFileSync(join(pkg, 'chem_wasm_lens_bg.wasm'));
const wasmB64    = wasmBytes.toString('base64');
const bindingsJs = readFileSync(join(pkg, 'chem_wasm_lens.js'), 'utf-8');

const bundle = `// chem-wasm-lens — self-contained ESM CDN bundle
// Generated by: node scripts/build_cdn.mjs — do not edit manually.
// Wasm (~411 KB) is inlined as base64; no external fetch required.
//
// Usage:
//   import { loadChem } from 'https://cdn.jsdelivr.net/npm/@kent-tokyo/chem-wasm-lens/dist/chem-wasm-lens.esm.js';
//   const { MolecularSystem } = await loadChem();

${bindingsJs}

// ── Inline Wasm loader ──────────────────────────────────────────────────────
const __WASM_B64 = '${wasmB64}';

function __decodeWasm(b64) {
  const s = atob(b64);
  const buf = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) buf[i] = s.charCodeAt(i);
  return buf.buffer;
}

let __loaded = null;

/**
 * Initialize the Wasm module and return all exports.
 * Safe to call multiple times — initialization runs only once.
 * No network request needed; Wasm is bundled inline.
 *
 * @returns {Promise<{MolecularSystem: typeof MolecularSystem}>}
 *
 * @example
 * import { loadChem } from 'https://cdn.jsdelivr.net/npm/@kent-tokyo/chem-wasm-lens/dist/chem-wasm-lens.esm.js';
 * const { MolecularSystem } = await loadChem();
 * const mol = MolecularSystem.from_smiles('CCO');
 */
export async function loadChem() {
  if (!__loaded) {
    __loaded = __wbg_init(__decodeWasm(__WASM_B64))
      .then(() => ({ MolecularSystem }));
  }
  return __loaded;
}
`;

mkdirSync(join(pkg, 'dist'), { recursive: true });
const outPath = join(pkg, 'dist', 'chem-wasm-lens.esm.js');
writeFileSync(outPath, bundle, 'utf-8');

const kb = Math.round(Buffer.byteLength(bundle, 'utf-8') / 1024);
console.log(`[build_cdn] pkg/dist/chem-wasm-lens.esm.js  ${kb} KB`);
